name: app02
description: "A new Flutter project."


publish_to: 'none'

version: 1.0.0+1


environment:
  sdk: ^3.7.2


dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.14.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  firebase_analytics: ^11.5.0

  animated_text_kit: ^4.2.2
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.2.8
  google_fonts: ^6.2.1
  email_validator: ^2.1.16
  iconsax_flutter: ^1.0.0
  font_awesome_flutter: ^10.4.0
  material_design_icons_flutter: ^7.0.7296
  flutter_feather_icons: ^2.0.0
  carousel_slider: ^5.0.0
  flutter_rating_bar: ^4.0.1




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0




# Top-Level Konfiguration f√ºr flutter_native_splash
flutter_native_splash:
      color: "#ffffff"
      image: assets/Logo/android-chrome-512x512.png
      android: true
      ios: true
      web: false



flutter:
  assets:
    - assets/images/leeren_profilefoto5.png
    - assets/Logo/android-chrome-512x512.png
    - assets/Logo/android-chrome-512x512-2.png
    - assets/Logo/android-chrome-512x512-3.png
    - assets/Logo/favicon-32x32.png
    - assets/Logo/favicon2-32x32.png
    - assets/Logo/favicon3-32x32.png
    - assets/icons/logout.png
    #kategories
    - assets/icons/Category_icons/mann.png
    - assets/icons/Category_icons/frau(1).png
    - assets/icons/Category_icons/kind.png
    - assets/icons/Category_icons/kleid.png
    - assets/icons/Category_icons/jacke(1).png
    - assets/icons/Category_icons/jacke(2).png
    #home
    - assets/images/home_bild1.jpg
    - assets/images/home_bild2.jpg
    - assets/images/home_bild3.jpg
    - assets/images/home_bild4.jpg
    - assets/images/home_bild5.jpg
    - assets/images/home_bild6.jpg
    - assets/images/home_bild7.jpg
    - assets/images/home_bild8.jpg
    - assets/images/home_bild9.jpg

      #review
    - assets/images/images.jpeg


  

  

  uses-material-design: true

  

  

  

  


  

  


  

  


  

  

  

  

  

  

  

  

  

  

  

  

  

  

  

  

  #
  

  

